network/urls.py
from django.urls import path

from . import views

app_name = 'network'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("compose", views.compose, name="compose"),
    path("user/<int:user_id>", views.profile, name="profile"),
    path("following/", views.following, name="following"),
    path("toggle_like/<int:post_id>", views.toggle_like, name="toggle_like"),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    follows = models.ManyToManyField(
        "self", blank=True, related_name="fans", symmetrical=False
    )

    def __str__(self):
        return self.username


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank=True, related_name='liked_posts')

network/views.py
import json
from lib2to3.fixes.fix_input import context

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import User, Post


def index(request):
    posts = Post.objects.all().order_by('-created')
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts_list = paginator.page(page_number)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)

    return render(request, "network/index.html", {
        "Posts": posts_list})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


@login_required
def compose(request):
    print(request.user.id)
    if request.method == "POST":
        print("I am reaching this point")
        try:
            data = json.loads(request.body)
            print("Data form compose: ", data)

            post = Post(
                author = request.user,
                body = data["body"]
            )
            post.save()

            return JsonResponse({"message": "Post created successfully."}, status=201)
        except KeyError:
            return JsonResponse({"error": "Invalid data."}, status=400)
    return JsonResponse({"error": "POST request required."}, status=400)


@login_required
def handle_followers(request, user_id):
    if request.method == "POST":
        try:
            viewed_user = get_object_or_404(User, pk=user_id)

            data = json.loads(request.body)
            action = data["action"]

            if action == "follow":
                viewed_user.following.add(request.user)
                return JsonResponse({"message": "Following user has been added."}, status=201)
            elif action == "unfollow":
                viewed_user.following.remove(request.user)
                return JsonResponse({"message": "Unfollowing user has been removed."}, status=201)
            else:
                return JsonResponse({"error": "Invalid action."}, status=400)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)
    return JsonResponse({"error": "POST request required."}, status=400)




@login_required
def emails(request):
    pass




@login_required
def profile(request, user_id):
    # IMPROVE!
    user = request.user
    viewed_user = get_object_or_404(User, pk=user_id)
    is_following = user.follows.filter(pk=user_id).exists()

    if request.method == "POST":
        current_user_profile = request.user
        if user_id != current_user_profile.id:
            if is_following:
                user.follows.remove(viewed_user)
                is_following = False

            else:
                user.follows.add(viewed_user)
                is_following = True

            context = {
                "user": user,
                "viewed_user": viewed_user,
                "is_following": is_following
            }

            user.save()
            return render(request, "network/profile.html", context)

    return render(request, "network/profile.html", {
        "user": request.user,
        "viewed_user": viewed_user,
        "is_following": is_following
    })


def following(request):
    user = request.user
    followed_users = user.follows.all()

    posts = Post.objects.filter(author__in=followed_users).order_by("-created")

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts_list = paginator.page(page_number)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)

    context = {
        "user": user,
        "Posts": posts_list
    }

    return render(request, "network/index.html", context)


@login_required()
def toggle_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user

    if user in post.likes.all():
        post.likes.remove(user)
        liked = False
    else:
        post.likes.add(user)
        liked = True

    return JsonResponse({
        "liked": liked,
        "like_count": post.likes.count()
    })


def edit_post(request, post_id):
    if request.method == "PUT":
        try:
            post = get_object_or_404(Post, pk=post_id)
            #new_content = request.POST["body"] # request.POST only for "FORMS"

            # Parse the request body as JSON
            data = json.loads(request.body.decode('utf-8'))  # Safely decode request body
            new_content = data.get("body", "")  # Get the 'body' field from the JSON data

            if new_content:
                post.body = new_content
                post.save()
                return JsonResponse({"Success": True, "message": "Post edited successfully."}, status=201)
            else:
                return JsonResponse({"Success": False, "message": "Content cannot be empty"}, status=400)
        except Post.DoesNotExist:
            return JsonResponse({"Success": False, "message": "Post does not exist."}, status=400)
    else:
        return JsonResponse({"Success": False, "message": "Invalid request method."}, status=400)

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    {% if user.is_authenticated %}

        <h2>All Posts</h2>

        <div class="listing">
            <h3>New Post</h3>
            <form id="compose-form" onsubmit="send_email()" method="post">
                {% csrf_token %}
                <textarea id="compose-body" placeholder="Write a new post...."></textarea>
                <input type="submit" value="Post">
            </form>
        </div>

        {% for post in Posts %}
            <div class="listing">
                <h4>
                    <a href="{% url 'network:profile' post.author.id %}">
                    {{ post.author }}
                    </a>
                </h4>
            
                {% if user == post.author %}
                    <button onclick="editPost({{ post.id }})">Edit</button>
                {% endif %}
            
                <div class="post-body">
                    <p id="body-{{ post.id }}">{{ post.body }}</p>
                </div>
                <p class="created-at">{{ post.created }}</p>
                <button onclick="handlerLike(this)" data-post-id="{{ post.id }}">
                    {% if user in post.likes.all %}
                        Unlike
                    {% else %}
                        Like
                    {% endif %}
                </button>
                
                <p>Likes: {{ post.likes.count }}</p>
                <p>Comment</p>
            </div>
        {% endfor %}

    {% endif %}

    <div class="pagination">
    <span class="step-links">
        {% if Posts.has_previous  %}
            <a href="?page={{ Posts.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
        Page {{ Posts.number }} of {{ Posts.paginator.num_pages }}
        </span>
    {% if Posts.has_next %}
        <a href="?page={{ Posts.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' user.id%}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    <script src="{% static 'network/inbox.js' %}"></script>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    {% if user.is_authenticated %}

        <h2>{{ viewed_user.username }}'s Profile</h2>

        <p>Followers: {{ viewed_user.fans.count }}</p>
        <p>Following: {{ viewed_user.follows.count }}</p>

        {% if user != viewed_user %}
            <form method="post" action="{% url 'network:profile' viewed_user.id %}">
            {% csrf_token %}
            {% if is_following %}
                <button type="submit">Unfollow</button>
            {% else %}
                <button type="submit">Follow</button>
            {% endif %}
            </form>
        {% endif %}

        {% for post in viewed_user.posts.all %}
            <div class="listing">
                <h4>
                    {{ viewed_user.username }}
                </h4>
                <p>{{ post.body }}</p>
                <p class="created-at">{{ post.created }}</p>
                <p>Likes: {{ post.likes }}</p>
                <p>Comment</p>
            </div>
        {% endfor %}

    {% endif %}

{% endblock %}


network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}